table Data
	lineageTag: 8e222679-99e3-40fa-8e9d-596553e8639d

	measure 'No of Patient' = DISTINCTCOUNT(Data[Patient Id])
		formatString: 0
		lineageTag: edd41b12-981b-4459-8d21-f5f03dd3f585

	measure 'Avg Wait time' = FORMAT( AVERAGE(Data[Patient Waittime]),"0.0")&"Min"
		lineageTag: 3e8dd103-5215-4c60-9a34-09abe837932a

	measure Rating = AVERAGE(Data[Patient Satisfaction Score])
		lineageTag: f0d9eaf4-0d27-4a9f-a798-28e920b1ec68

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'No of Referrals' = CALCULATE(COUNTROWS(Data),Data[Department Referral]<>"None")
		formatString: 0
		lineageTag: 7cfe1ece-1fb2-48ac-a758-79ea33d58b93

	column 'Patient Id'
		dataType: string
		lineageTag: f4150320-ed3f-4fa8-95ce-2024d96ac487
		summarizeBy: none
		sourceColumn: Patient Id

		annotation SummarizationSetBy = Automatic

	column 'Patient First Inital'
		dataType: string
		lineageTag: a38e9116-55b0-4f1d-a76a-31001a468e20
		summarizeBy: none
		sourceColumn: Patient First Inital

		annotation SummarizationSetBy = Automatic

	column 'Patient Last Name'
		dataType: string
		lineageTag: afcb6c1b-f39b-439f-acd5-3f10fe304622
		summarizeBy: none
		sourceColumn: Patient Last Name

		annotation SummarizationSetBy = Automatic

	column 'Patient Gender'
		dataType: string
		lineageTag: 3619a330-0fe4-415e-9af6-1afedaabc9f9
		summarizeBy: none
		sourceColumn: Patient Gender

		annotation SummarizationSetBy = Automatic

	column 'Patient Age'
		dataType: int64
		formatString: 0
		lineageTag: be6cbc82-841b-4188-ab4b-6ff31944712f
		summarizeBy: sum
		sourceColumn: Patient Age

		annotation SummarizationSetBy = Automatic

	column 'Patient Race'
		dataType: string
		lineageTag: 6d4d8881-c78f-4961-b924-14e7d7c7daec
		summarizeBy: none
		sourceColumn: Patient Race

		annotation SummarizationSetBy = Automatic

	column 'Department Referral'
		dataType: string
		lineageTag: 7250196e-65b5-4c3e-ab2b-b722570c8205
		summarizeBy: none
		sourceColumn: Department Referral

		annotation SummarizationSetBy = Automatic

	column 'Patient Admission Flag'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 1f55ecb2-cbea-4fc1-aaea-2e2f3ddbb420
		summarizeBy: none
		sourceColumn: Patient Admission Flag

		annotation SummarizationSetBy = Automatic

	column 'Patient Satisfaction Score'
		dataType: int64
		formatString: 0
		lineageTag: 6894a3d2-f56b-43f9-b135-c385d4af14ec
		summarizeBy: sum
		sourceColumn: Patient Satisfaction Score

		annotation SummarizationSetBy = Automatic

	column 'Patient Waittime'
		dataType: int64
		formatString: 0
		lineageTag: a75ff91e-edc0-44a0-a73c-69e54d8fc27d
		summarizeBy: sum
		sourceColumn: Patient Waittime

		annotation SummarizationSetBy = Automatic

	column 'Patients CM'
		dataType: int64
		formatString: 0
		lineageTag: 947a9f1f-ad20-447c-80f5-6d81a542b50d
		summarizeBy: sum
		sourceColumn: Patients CM

		annotation SummarizationSetBy = Automatic

	column 'Patient Full Name'
		dataType: string
		lineageTag: 42c5444d-5255-41dc-8232-7c0ef6428e8b
		summarizeBy: none
		sourceColumn: Patient Full Name

		annotation SummarizationSetBy = Automatic

	column 'Patient Admission Time'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 77549b1c-b5ee-4dec-b38b-458022a8804b
		summarizeBy: none
		sourceColumn: Patient Admission Time

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Admission Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a4aa8fc4-92bc-4c90-b39e-166434c9214e
		summarizeBy: none
		sourceColumn: Admission Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Data = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\Power BI\Projects\HealthDomain\resources\Data.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Patient Id", type text}, {"Patient Admission Date", type text}, {"Patient First Inital", type text}, {"Patient Last Name", type text}, {"Patient Gender", type text}, {"Patient Age", Int64.Type}, {"Patient Race", type text}, {"Department Referral", type text}, {"Patient Admission Flag", type logical}, {"Patient Satisfaction Score", Int64.Type}, {"Patient Waittime", Int64.Type}, {"Patients CM", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Patient Full Name", each [Patient First Inital] & " " & [Patient Last Name]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom","M","Male",Replacer.ReplaceText,{"Patient Gender"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"Patient Gender"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","NC","Not Confirmed",Replacer.ReplaceText,{"Patient Gender"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Replaced Value2", "Patient Admission Date", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Patient Admission Date.1", "Patient Admission Date.2"}),
				    #"Split Column by Delimiter1" = Table.SplitColumn(#"Split Column by Delimiter", "Patient Admission Date.1", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"Patient Admission Date.1.1", "Patient Admission Date.1.2", "Patient Admission Date.1.3"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Split Column by Delimiter1",{{"Patient Admission Date.1.1", Int64.Type}, {"Patient Admission Date.1.2", Int64.Type}, {"Patient Admission Date.1.3", Int64.Type}, {"Patient Admission Date.2", type time}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Admission Date", each [Patient Admission Date.1.3]& "-"&[Patient Admission Date.1.2]&""&[Patient Admission Date.1.1]),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Patient Admission Date.1.1", type text}, {"Patient Admission Date.1.2", type text}, {"Patient Admission Date.1.3", type text}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Admission Date.1", each [Patient Admission Date.1.3]&"-"&[Patient Admission Date.1.2]&"-"&[Patient Admission Date.1.1]),
				    #"Removed Columns" = Table.RemoveColumns(#"Added Custom2",{"Admission Date"}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Removed Columns",{{"Admission Date.1", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type3",{{"Admission Date.1", "Admission Date"}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Renamed Columns",{"Patient Admission Date.1.1", "Patient Admission Date.1.2", "Patient Admission Date.1.3"}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Removed Columns1",{{"Patient Admission Date.2", "Patient Admission Time"}})
				in
				    #"Renamed Columns1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

